/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PeriodsRouteImport } from './routes/periods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ClassroomsRouteImport } from './routes/classrooms'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsRoute = ClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/classrooms': typeof ClassroomsRoute
  '/courses': typeof CoursesRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/classrooms': typeof ClassroomsRoute
  '/courses': typeof CoursesRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/classrooms': typeof ClassroomsRoute
  '/courses': typeof CoursesRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/periods': typeof PeriodsRoute
  '/reports': typeof ReportsRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/calendar'
    | '/classrooms'
    | '/courses'
    | '/enrollment'
    | '/login'
    | '/periods'
    | '/reports'
    | '/scheduler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/calendar'
    | '/classrooms'
    | '/courses'
    | '/enrollment'
    | '/login'
    | '/periods'
    | '/reports'
    | '/scheduler'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/calendar'
    | '/classrooms'
    | '/courses'
    | '/enrollment'
    | '/login'
    | '/periods'
    | '/reports'
    | '/scheduler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CalendarRoute: typeof CalendarRoute
  ClassroomsRoute: typeof ClassroomsRoute
  CoursesRoute: typeof CoursesRoute
  EnrollmentRoute: typeof EnrollmentRoute
  LoginRoute: typeof LoginRoute
  PeriodsRoute: typeof PeriodsRoute
  ReportsRoute: typeof ReportsRoute
  SchedulerRoute: typeof SchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms': {
      id: '/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CalendarRoute: CalendarRoute,
  ClassroomsRoute: ClassroomsRoute,
  CoursesRoute: CoursesRoute,
  EnrollmentRoute: EnrollmentRoute,
  LoginRoute: LoginRoute,
  PeriodsRoute: PeriodsRoute,
  ReportsRoute: ReportsRoute,
  SchedulerRoute: SchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
